// ─────────────────────────────────────────────────────────────
// scripts/mcp/wagTruth.test.mjs  | valet
// Repo-wide truth-in-advertising gate for the Web Action Graph
// (MCP-TRUTH S11 + ruling R24; audit "marketed vaporware" finding).
//
// The WAG has zero implementation, so every tracked mention of
// "Action Graph" must carry roadmap/planned framing on the same
// line or a nearby line (±FRAME_WINDOW): 'planned', 'roadmap',
// or 'not implemented' (case-insensitive).
//
// Scope: all git-tracked files EXCEPT dx/plans/** (audit/plan
// prose), CHANGELOG* (historical record), **/mcp-data/**
// (generated corpus — regenerated by mcp:build from already-gated
// sources), and this gate itself (fixtures below are deliberately
// unframed).
//
// NOTE (Wave 0.4): GOVERNANCE S2/S3 roadmap-marks AGENTS.md,
// MainPage.tsx and Quickstart.tsx in a parallel lane — this gate
// may be red on those files mid-wave and must be green at wave end.
// ─────────────────────────────────────────────────────────────
import { describe, it, expect } from 'vitest';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// ── gate logic (pure; fixture-tested below) ──────────────────

/** Lines mentioning the WAG, in any of its spellings. */
const MENTION_RE = /\baction[\s-]graph\b/i;
/** Framing that makes a mention honest (per S11's pragmatic token set). */
const FRAMING_RE = /\b(?:planned|roadmap|not\s+implemented)\b/i;
/** A nearby line = within this many lines either side of the mention. */
const FRAME_WINDOW = 5;

/**
 * Scan one file's lines; return the unframed Action Graph mentions.
 * @param {string[]} lines
 * @returns {Array<{ line: number, text: string }>} 1-based offenders
 */
export function findUnframedMentions(lines) {
  const offenders = [];
  for (let i = 0; i < lines.length; i++) {
    if (!MENTION_RE.test(lines[i])) continue;
    const lo = Math.max(0, i - FRAME_WINDOW);
    const hi = Math.min(lines.length - 1, i + FRAME_WINDOW);
    let framed = false;
    for (let j = lo; j <= hi && !framed; j++) framed = FRAMING_RE.test(lines[j]);
    if (!framed) offenders.push({ line: i + 1, text: lines[i].trim() });
  }
  return offenders;
}

// ── repo scan plumbing ───────────────────────────────────────

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const SELF = 'scripts/mcp/wagTruth.test.mjs';

/** @param {string} rel git-tracked path, forward slashes */
export function isExcluded(rel) {
  if (rel === SELF) return true; // fixtures here are intentionally unframed
  if (rel.startsWith('dx/plans/')) return true;
  if (rel.split('/').includes('mcp-data')) return true;
  if (path.posix.basename(rel).toUpperCase().startsWith('CHANGELOG')) return true;
  return false;
}

function trackedFiles() {
  const out = execFileSync('git', ['ls-files', '-z'], { cwd: REPO_ROOT, encoding: 'utf8' });
  return out.split('\0').filter(Boolean);
}

// ── fixture tests for the gate logic ─────────────────────────

describe('wag truth gate — logic fixtures', () => {
  it('flags a bare present-tense mention', () => {
    const lines = ['valet ships a Web Action Graph capturing every interaction.'];
    expect(findUnframedMentions(lines)).toEqual([
      { line: 1, text: 'valet ships a Web Action Graph capturing every interaction.' },
    ]);
  });

  it('accepts same-line framing, any listed token, any case', () => {
    for (const ok of [
      'Web Action Graph (planned)',
      'Roadmap: the Web Action Graph will capture interactions.',
      'Planned — not implemented. The action graph is conceptual.',
      'web action-graph — NOT IMPLEMENTED yet',
    ]) {
      expect(findUnframedMentions([ok])).toEqual([]);
    }
  });

  it('accepts framing on a nearby line within the window (glossary-entry shape)', () => {
    const lines = [
      '  {',
      "    term: 'Web Action Graph',",
      "    aliases: ['action graph', 'WAG'],",
      "    category: 'ai',",
      '    definition:',
      "      'Planned — not implemented. A conceptual graph of actions.',",
      '  },',
    ];
    // mentions on lines 2 and 3; framing on line 6 → within ±5
    expect(findUnframedMentions(lines)).toEqual([]);
  });

  it('rejects framing outside the window', () => {
    const lines = [
      'Roadmap',
      ...Array(FRAME_WINDOW).fill('filler line'),
      'The Web Action Graph records everything.',
    ];
    expect(findUnframedMentions(lines)).toHaveLength(1);
    expect(findUnframedMentions(lines)[0].line).toBe(FRAME_WINDOW + 2);
  });

  it('does not treat framing-token lookalikes as framing', () => {
    // substrings inside larger words ('unplanned', 'roadmaps') are not
    // framing — FRAMING_RE requires the bare token at word boundaries
    expect(findUnframedMentions(['an unplanned Action Graph rollout'])).toHaveLength(1);
    expect(findUnframedMentions(['roadmapsy Action Graph prose'])).toHaveLength(1);
  });

  it('flags hyphen/case variants of the mention itself', () => {
    expect(findUnframedMentions(['see the action-graph module'])).toHaveLength(1);
    expect(findUnframedMentions(['ACTION GRAPH telemetry'])).toHaveLength(1);
  });

  it('ignores unrelated text and bare "WAG" (alias gated only next to its term)', () => {
    expect(findUnframedMentions(['interaction graph of actions', 'WAG'])).toEqual([]);
  });
});

describe('wag truth gate — exclusions', () => {
  it('excludes exactly the sanctioned paths', () => {
    expect(isExcluded('dx/plans/valet-overhaul-2026-06-10/audit.md')).toBe(true);
    expect(isExcluded('CHANGELOG.md')).toBe(true);
    expect(isExcluded('packages/valet-mcp/CHANGELOG.md')).toBe(true);
    expect(isExcluded('mcp-data/glossary.json')).toBe(true);
    expect(isExcluded('packages/valet-mcp/mcp-data/glossary.json')).toBe(true);
    expect(isExcluded(SELF)).toBe(true);

    expect(isExcluded('README.md')).toBe(false);
    expect(isExcluded('AGENTS.md')).toBe(false);
    expect(isExcluded('docs/AGENTS.md')).toBe(false);
    expect(isExcluded('dx/RELEASING.md')).toBe(false);
    expect(isExcluded('docs/src/pages/getting-started/Glossary.tsx')).toBe(false);
  });
});

// ── the repo-wide acceptance gate ────────────────────────────

describe('wag truth gate — repository scan', () => {
  it('every tracked Action Graph mention carries roadmap/planned framing', () => {
    const offenders = [];
    for (const rel of trackedFiles()) {
      if (isExcluded(rel)) continue;
      let content;
      try {
        content = fs.readFileSync(path.join(REPO_ROOT, rel), 'utf8');
      } catch {
        continue; // deleted-but-staged etc.
      }
      if (content.includes('\u0000')) continue; // binary
      for (const hit of findUnframedMentions(content.split(/\r?\n/))) {
        offenders.push(`${rel}:${hit.line}: ${hit.text}`);
      }
    }
    expect(
      offenders,
      'Unframed "Action Graph" mentions (add planned/roadmap/not-implemented framing ' +
        `on the line or within ${FRAME_WINDOW} lines):\n` +
        offenders.join('\n'),
    ).toEqual([]);
  });
});
